# Состояния
(
    WAITING_PHONE,
    ADDING_DRIVER_PHONE,
    ADDING_DRIVER_NAME,
    ADDING_CAR_NUMBER,
    ADDING_CAR_BRAND,
    ADDING_CAR_MODEL,
    ADDING_CAR_FUEL,
    ADDING_CAR_MILEAGE,
    CHOOSING_CAR,
    ENTERING_START_MILEAGE,
    TAKING_ODOMETER_PHOTO,
    TAKING_FUEL_PHOTOS,
    TAKING_OIL_PHOTO,
    TAKING_CABIN_PHOTO,
    ENTERING_END_MILEAGE,
    TAKING_END_ODOMETER_PHOTO,
) = range(16)
